### ISSUE TITLE
Retrieving All Listings from ItemRequest? Issue with getRawResponse?

### ISSUE THREAD

**Issue by bruman2012** [nathanoertel/walmart-seller-api-php#1]
Hi,

I've been messing around with this for a bit and am looking for some advice.
Currently on PHP 7.3.

I am loading this package via a composer local modification (as this is not on packagist), and to retrieve all my listings I am attempting the following code:

```
require_once 'vendor/autoload.php';

use WalmartSellerAPI\Library;
use WalmartSellerAPI\util\XSDParser;

$config = array('clientId' => WALMART_CONSUMER_ID,
                'clientSecret' => WALMART_SECRET);

    $feed = new WalmartSellerAPI\ItemRequest($config);
    $items = $feed->get('?');
```

This is working, but with some heavy modification of core files.
Specifically `AbstractRequest.php` and the `request()` function.

I am getting a successful XML response but only when I modify the request function and comment out everything and including `$responseClass = $this->getRawResponse();`

		$response = curl_exec($curl);
		$information = curl_getinfo($curl);
		$this->log($information['request_header']);

		if($response !== false) {
            $headerSize = curl_getinfo($curl, CURLINFO_HEADER_SIZE);
            $headers = substr($response, 0, $headerSize);
            $body = substr($response, $headerSize);
//			$responseClass = $this->getRawResponse();
//			$result = new $responseClass($headers, $body, $method);
//			if($result->isSuccess()) {
//				$this->log($headers);
//				$this->log($this->formatXml($body));
//			} else {
//				$this->log($response);
//			}
//			unset($headerSize, $headers, $body);
//			if(!$result->isSuccess() && $result->getError() == 'RateLimitedException') {
//				throw new \Exception($result->getErrorMessage(), $result->getErrorCode());
//			}
//		} else {
//			$this->log(curl_error($curl));
//		}

            curl_close($curl);

            return $body;
        }
		else {
		    return null;
        }

The variable `$body` is indeed getting the proper XML response, but anytime I attempt to use the getRawResponse function, I receive an error:

`Fatal error: Uncaught Error: Call to undefined method WalmartSellerAPI\ItemRequest::getRawResponse() in /home/vendor/digitalclouddesigns/walmart-seller-api-php/src/AbstractRequest.php:134 Stack trace: #0 /home/vendor/digitalclouddesigns/walmart-seller-api-php/src/AbstractRequest.php(63): WalmartSellerAPI\AbstractRequest->request('GET', '?', Array) #1 /home/public_html/app/sandbox/walmart2.php(13): WalmartSellerAPI\AbstractRequest->get('?') #2 {main} thrown in /home/vendor/digitalclouddesigns/walmart-seller-api-php/src/AbstractRequest.php on line 134
`
So my only method of receiving the response is to bypass this entirely.  What am I doing wrong and how can I get a successful response going through all the code functions?

**Comment by bruman2012** [comment]
Nevermind, closing.  I see you made updates to the code and it is working perfectly now.  Thank you.

**Comment by nathanoertel** [comment]
@bruman2012 There's also a new named method to get the item list.  It doesn't do anything more than what you're doing but it makes it a little more clear what the method does.  You can add search parameters or offsets or keep listing them using the nextCursor parameter that is returned:

`$itemResponse = $itemRequest->items($params);`

**Comment by bruman2012** [comment]
Thanks man that is cleaner and works great.

FYI - there is also an issue with `PriceRequest.php`

Line 7
`$p = new WalmartSellerAPI\model\Price();`

`Uncaught Error: Class 'WalmartSellerAPI\WalmartSellerAPI\model\Price' not found`

Still looking into to try and fix myself.

**Comment by nathanoertel** [comment]
@bruman2012 Try the latest update.  It should work correctly now.

**Comment by bruman2012** [comment]
@nathanoertel Thanks much.  Class error is gone, but am getting an error in the actual request.

Any idea?

```
object(WalmartSellerAPI\PriceResponse)#8 (10) {
  ["data":protected]=>
  NULL
  ["success":"WalmartSellerAPI\AbstractResponse":private]=>
  bool(false)
  ["error":"WalmartSellerAPI\AbstractResponse":private]=>
  string(0) ""
  ["errorCode":"WalmartSellerAPI\AbstractResponse":private]=>
  string(16) "500.SYSTEM_ERROR"
  ["errorMessage":"WalmartSellerAPI\AbstractResponse":private]=>
  string(14) "Internal error"
  ["count":"WalmartSellerAPI\AbstractResponse":private]=>
  int(0)
  ["offset":"WalmartSellerAPI\AbstractResponse":private]=>
  int(0)
  ["limit":"WalmartSellerAPI\AbstractResponse":private]=>
  int(100)
  ["response":"WalmartSellerAPI\AbstractResponse":private]=>
  string(462) "<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:errors xmlns:ns2="http://walmart.com/">
    <ns2:error>
        <ns2:code>500.SYSTEM_ERROR</ns2:code>
        <ns2:description>Internal error</ns2:description>
        <ns2:info>System encountered some internal error.</ns2:info>
        <ns2:severity>ERROR</ns2:severity>
        <ns2:category>SYSTEM</ns2:category>
        <ns2:causes/>
        <ns2:errorIdentifiers/>
    </ns2:error>
</ns2:errors>

  ["headers":"WalmartSellerAPI\AbstractResponse":private]=>
  array(28) {
    ["http_code"]=>
    string(20) "HTTP/1.1 520 Unknown"
    ["Accept-Ranges"]=>
    string(5) "bytes"
    ["Content-Length"]=>
    string(3) "462"
    ["Content-Type"]=>
    string(30) "application/xml; version="1.0""
    ["Method"]=>
    string(4) "null"
    ["Uri"]=>
    string(4) "null"
    ["WM_CONSUMER.ID"]=>
    string(36) "XXXXXX"
    ["WM_CONSUMER.INTIMESTAMP"]=>
    string(0) ""
    ["WM_QOS.CORRELATION_ID"]=>
    string(24) "XXXXXX"
    ["WM_SEC.AUTH_TOKEN"]=>
    string(0) ""
    ["WM_SEC.REFRESH_AUTH_TOKEN"]=>
    string(0) ""
    ["WM_SVC.CLASS_NAME"]=>
    string(76) "com.walmart.services.impl.GMPGatewayService$$EnhancerBySpringCGLIB$$9f6ffac1"
    ["WM_SVC.ENV"]=>
    string(4) "prod"
    ["WM_SVC.INTIMESTAMP"]=>
    string(13) "1569342647395"
    ["WM_SVC.METHOD_NAME"]=>
    string(8) "doPutAPI"
    ["WM_SVC.NAME"]=>
    string(19) "Walmart Marketplace"
    ["WM_SVC.OUTTIMESTAMP"]=>
    string(13) "1569342647413"
    ["WM_SVC.SERVER_IP"]=>
    string(13) "10.47.109.176"
    ["WM_SVC.SERVER_NAME"]=>
    string(39) "PartnerGMPService-XXXXXX"
    ["WM_SVC.VERSION"]=>
    string(0) ""
    ["X-Tb-Error"]=>
    string(17) "DebugInfoDisabled"
    ["X-Tb-Originstatus-Dfw-Appblx228-07"]=>
    string(3) "500"
    ["Expires"]=>
    string(29) "Tue, 24 Sep 2019 16:30:47 GMT"
    ["Cache-Control"]=>
    string(29) "max-age=0, no-cache, no-store"
    ["Pragma"]=>
    string(8) "no-cache"
    ["Date"]=>
    string(29) "Tue, 24 Sep 2019 16:30:47 GMT"
    ["Connection"]=>
    string(5) "close"
    ["Set-Cookie"]=>
    string(133) "XXXXXX; Path=/; Secure"
  }
}
```

**Comment by bruman2012** [comment]
Headers:


```
PUT

            [0] => Content-Type: application/xml; boundary=<?xml version="1.0"?>
            [1] => WM_CONSUMER.CHANNEL.TYPE: XXXXXXXXXXXXX
            [2] => Accept: application/xml
            [3] => Authorization: Basic XXXXXXXXXXXXXXXXXX
            [4] => WM_SVC.NAME: Walmart Marketplace
            [5] => WM_SEC.ACCESS_TOKEN: XXXXXXXXXXXXXXXXX
            [6] => WM_SEC.TIMESTAMP: 1569342920300
            [7] => WM_QOS.CORRELATION_ID: XXXXXXXXXXXXXXXX
```

I'm trying to check out the documentation

https://developer.walmart.com/#/apicenter/marketPlace/latest#updateAPrice

The request the API is sending is:

```
<?xml version="1.0"?>
<Price xmlns="http://walmart.com/">
<itemIdentifier>
    <sku>SKU-NAME PX0480</sku>
</itemIdentifier>
<pricingList>
    <pricing>
        <currentPrice>
            <value amount="99.93"/>
        </currentPrice>
    </pricing>
</pricingList>
</Price>
```

Looking at the example given

```
<Price xmlns="http://walmart.com/">
  <itemIdentifier>
    <sku>sku-656666666</sku>
  </itemIdentifier>
  <pricingList>
    <pricing>
      <currentPrice>
        <value currency="USD" amount="4.00" />
      </currentPrice>
    </pricing>
  </pricingList>
</Price>
```

Still not sure of solution, just throwing out some more info.

**Comment by nathanoertel** [comment]
What is the issue?  The only difference is the lack of the currency attribute which defaults to USD according to the XSD.  What error is being returned?

**Comment by bruman2012** [comment]
Yeah I noticed that... wasn't sure if it was required or not, but revised PriceRequest.php to include the currency attribute and it still gives the same error, so that's not it.

Error is

 ```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:errors xmlns:ns2="http://walmart.com/">
    <ns2:error>
        <ns2:code>500.SYSTEM_ERROR</ns2:code>
        <ns2:description>Internal error</ns2:description>
        <ns2:info>System encountered some internal error.</ns2:info>
        <ns2:severity>ERROR</ns2:severity>
        <ns2:category>SYSTEM</ns2:category>
        <ns2:causes/>
        <ns2:errorIdentifiers/>
    </ns2:error>
</ns2:errors>
```
AbstractResponse message gives back an `"HTTP/1.1 520 Unknown"`

I guess this indicates a bad request... I am looking over everything though and am not seeing anything that shouldn't be there.  Only difference I noticed was the Content-Type in the header, but don't think that should matter?

My only other guess might be my WM_CONSUMER.CHANNEL.TYPE could not be correct? I regenerated my keys.. but can't find this on the API homepage.. still looking into it.. not sure if it's the request or my own credentials yet.

**Comment by bruman2012** [comment]
Nah can't be my credentials, I am using the same to retrieve Orders and that works perfectly fine.

Looked into it some more.. can't pinpoint anything at the moment.  I'll let you know though.

Here's the script I am using if you notice anything that may be causing this

```
use WalmartSellerAPI\Library;
use WalmartSellerAPI\util\XSDParser;

$newprice = $_POST['price'];
$itemid = $_POST['itemid'];
$sku = $_POST['sku'];

$config = array('clientId' => WALMART_CONSUMER_ID2,
    'clientSecret' => WALMART_SECRET2,
    'channelTypeId' => WALMART_CHANNEL_TYPE);

$item = new WalmartSellerAPI\PriceRequest($config);

var_dump($item);

$updateprice = $item->update($sku, $newprice);

var_dump($updateprice);
```

**Comment by nathanoertel** [comment]
@bruman2012 It was the content type, pull the latest update.  I have only been using the bulk price update via feed method for price updates.

**Comment by bruman2012** [comment]
Okay, great!

Also funny you mention the bulk price update, I was just going to use that as a work-around because I was unsure about the single method.

```
$config = array('clientId' => WALMART_CONSUMER_ID2,
    'clientSecret' => WALMART_SECRET2,
    'channelTypeId' => WALMART_CHANNEL_TYPE);

    $skuarray = array('LA2' => array('price' => '49.99'));

    $item = new WalmartSellerAPI\FeedRequest($config);

    $orders = $item->bulkUpdatePricing($skuarray);
```

Works great, 200 response, instant.
And you can include a single sku in this as well so there really isn't much of a point to the previous single request.

Anyways -- thanks for all the effort and talk, awesome work with this.  By far my favorite Walmart API PHP SDK, and I looked over almost all of them trying to find one with the updated API version I could get along with.  Good stuff.
